/// <reference types="node" />
/* eslint-disable no-console */
import fs from 'node:fs';
import path from 'node:path';
import {
  breakpoints,
  colors,
  fontSizes,
  fontWeights,
  lineHeights,
  radii,
  spacing,
  transitions,
  zIndices,
} from '@sincroniza/tokens';

function generateCssTokens() {
  const outputPath = path.resolve(
    import.meta.dirname,
    '../src/styles/tokens.css',
  );

  let cssContent = `/* ==========================================================================\n`;
  cssContent += `   DO NOT EDIT: This file is automatically generated from @sincroniza/tokens\n`;
  cssContent += `   ========================================================================== */\n\n`;

  cssContent += `:root {\n`;

  const appendTokens = (
    prefix: string,
    tokenGroup: Record<string, string | number>,
  ) => {
    Object.entries(tokenGroup).forEach(([key, value]) => {
      cssContent += `  --${prefix}-${key}: ${String(value)};\n`;
    });
  };

  appendTokens('spacing', spacing);
  appendTokens('radii', radii);
  appendTokens('font-size', fontSizes);
  appendTokens('font-weight', fontWeights);
  appendTokens('line-height', lineHeights);
  appendTokens('z-index', zIndices);
  appendTokens('breakpoint', breakpoints);
  appendTokens('transition', transitions);

  Object.entries(colors).forEach(([key, value]) => {
    if (typeof value === 'object') {
      if (key === 'darkGray') return;

      Object.entries(value).forEach(([subKey, subValue]) => {
        if (subKey === 'white' || subKey === 'black') {
          cssContent += `  --color-${subKey}: ${subValue};\n`;
        } else {
          cssContent += `  --color-${key}-${subKey}: ${subValue};\n`;
        }
      });
    } else {
      cssContent += `  --color-${key}: ${value};\n`;
    }
  });
  cssContent += `}\n\n`;

  if ('darkGray' in colors) {
    cssContent += `[data-theme='dark'] {\n`;
    Object.entries(colors.darkGray as Record<string, string>).forEach(
      ([subKey, subValue]) => {
        if (subKey === 'white' || subKey === 'black') {
          cssContent += `  --color-${subKey}: ${subValue};\n`;
        } else {
          cssContent += `  --color-gray-${subKey}: ${subValue};\n`;
        }
      },
    );
    cssContent += `}\n`;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, cssContent, 'utf-8');
  console.log('Design tokens successfully compiled into tokens.css');
}

generateCssTokens();
